steps:
  # Étape 1: Construire l'image Docker
  # On utilise le "short SHA" (l'identifiant court du commit git) pour versionner chaque image.
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'europe-west9-docker.pkg.dev/$PROJECT_ID/flower-app-images/back-flower-app:$SHORT_SHA'
      - '.'

  # Étape 2: Pousser (envoyer) l'image vers Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west9-docker.pkg.dev/$PROJECT_ID/flower-app-images/back-flower-app:$SHORT_SHA']

  # Étape 3: Déployer la nouvelle image sur Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'back-flower-app' # Le nom de votre service Cloud Run
      - '--image=europe-west9-docker.pkg.dev/$PROJECT_ID/flower-app-images/back-flower-app:$SHORT_SHA'
      - '--region=europe-west9'
      - '--memory=2Gi' # On conserve l'allocation de mémoire
      - '--platform=managed'


options:
  logging: CLOUD_LOGGING_ONLY
